# Основная информация о плагине
name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}.BukkitPluginMain
version: ${project.version}
author: rubukkit.org
website: http://www.rubukkit.org
# Обязательные зависимости (пример)
#depend:
#  - WorldEdit
#  - WorldGuard
# Необязательные зависимости (пример)
#softdepend:
#  - Vault
# Зарегистрированные команды
#commands:
#  templatecommand:
#    description: ${project.artifactId} command hub
#    usage: /<command> do what?
# Зарегистрированные права
#permissions:
#  RUBUKKIT_TEMPLATE.admin:
#    description: Access to all functions
#    default: op
#    children:
#     RUBUKKIT_TEMPLATE.someperm: true
