# Основная информация о плагине
# Получается из pom.xml при сборке, поэтому не удаляйте из него упомянутые здесь поля
name:    ${project.artifactId}
main:    ${project.groupId}.${project.artifactId}.BukkitPluginMain
version: ${project.version}
author:  rubukkit.org
website: ${project.url}
# Обязательные зависимости (пример)
#depend:
#  - WorldEdit
#  - WorldGuard
# Необязательные зависимости (пример)
#softdepend:
#  - Vault
# Зарегистрированные команды
commands:
  rbtmplt:
    description: ${project.artifactId} command hub
    usage: /<command> do what?
# Зарегистрированные права
permissions:
  rbtmplt.admin:
    description: Доступ ко всем функциям плагина без ограничения
    default: op
    children:
     rbtmplt.testperm: true
  rbtmplt.testperm:
    description: Для проверки /rbtmplt testperm
    default: op
